export const FETCH_ENTRIES = 'FETCH_ENTRIES';
export const FETCH_USER_CONTACTS = 'FETCH_USER_CONTACTS';
export const NEW_ENTRY = 'NEW_ENTRY'
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const ROW_SELECTED = 'ROW_SELECTED';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const LOAD_ENTRY = 'LOAD_ENTRY';

export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const NEW_CAMPAIGN = 'NEW_CAMPAIGN';
export const EDIT_CAMPAIGN = 'EDIT_CAMPAIGN';
export const ACTIVE_CAMPAIGN = 'ACTIVE_CAMPAIGN';
export const LOAD_CAMPAIGN = 'LOAD_CAMPAIGN';
export const ARCHIVED_CAMPAIGN = 'ARCHIVED_CAMPAIGN';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_UP_USER = 'SIGN_UP_USER';