export const FETCH_ENTRIES = 'FETCH_ENTRIES';
export const NEW_ENTRY = 'NEW_ENTRY'
export const DELETE_ENTRY = 'DELETE_ENTRY';

export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const NEW_CAMPAIGN = 'NEW_CAMPAIGN';
export const EDIT_CAMPAIGN = 'EDIT_CAMPAIGN';